### ISSUE TITLE
sample of Array in Line20 Gotcha.rb

### ISSUE THREAD

**Issue by marcometz** [seejohnrun/gotcha#3]
The method sample:Array only exists in ruby 1.9.2 and not in 1.8.7

Gotcha.rb
20|    if !@gotcha_types.nil? && type = @gotcha_types.sample 

is there another way of implementing a random item of an array?

**Comment by seejohnrun** [comment]
Thanks for reporting this.  The issue has been fixed in Gotcha 0.0.5 by commit a51318c3e13de859297c97e2f0446ebf6c4f1172

**Comment by seejohnrun** [comment]
PS: I'm interested in the possibility of taking your locale translations of my questions as a pull request.  Is that okay?

**Comment by marcometz** [comment]
Thanks for this fast response... and yes, locale translations would be the nicer way... glad to see this :-)
